no checks on build + gosec

diff --git a/.github/workflows/golang-sast.yaml b/.github/workflows/golang-sast.yaml
--- a/.github/workflows/golang-sast.yaml
+++ b/.github/workflows/golang-sast.yaml
@@ -152,6 +152,47 @@ jobs:
         go mod download
 
     - name: Run govulncheck
+      id: govulncheck_scan
+      uses: golang/govulncheck-action@v1
+      with:
+        go-version-input: ${{ inputs.go-version }}
+        check-latest: true
+        output-format: sarif
+
+    - name: upload govulncheck scan SARIF report
+      uses: github/codeql-action/upload-sarif@v2
+      with:
+        sarif_file: ${{ steps.govulncheck_scan.outputs.sarif }}
+
+  gosec:
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+
+    steps:
+    - uses: actions/checkout@v4
+
+    - name: Setup Go
+      uses: actions/setup-go@v5
+      with:
+        go-version: ${{ inputs.go-version }}
+
+    - name: Configure git for private modules
       run: |
-        go install golang.org/x/vuln/cmd/govulncheck@latest
-        govulncheck ./...
+        [ ! -z "${{ secrets.go-token }}" ] && git config --global url."https://${{ secrets.go-token }}@github.com".insteadOf "https://github.com" || true
+
+    - name: Download dependencies
+      run: |
+        go mod download
+
+    - name: Run Gosec Security Scanner
+      uses: securego/gosec@master
+      with:
+        # we let the report trigger content trigger a failure using the GitHub Security features.
+        args: '-no-fail -fmt sarif -out results.sarif ./...'
+
+    - name: Upload SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+      with:
+        sarif_file: results.sarif
+
+
